### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by francesco-dipi** [francesco-dipi/note-transposer#1]
This project has not been updated in years. Although it works and it is used at least by me; the dependencies used ([jquery](https://jquery.com/) and [bootstrap](https://getbootstrap.com/)) should be updated to the latest versions available.

**Comment by fastboot** [comment]
I'll update them can you assign it to me @francesco-dipi ?

**Comment by fastboot** [comment]
@francesco-dipi I have updated the dependencies here's a link to the PR: [Link](https://github.com/francesco-dipi/transposer/pull/4) please have a look

**Comment by francesco-dipi** [comment]
Ok thanks
