### ISSUE TITLE
Add dark mode switch

### ISSUE THREAD

**Issue by francesco-dipi** [francesco-dipi/note-transposer#2]
A nice touch to add would be a dark mode, handled by a switch.
I've found this [project](https://www.jqueryscript.net/other/dark-mode-bootstrap.html) that can be used.

**Comment by fastboot** [comment]
I can have a look can you assign it to me?

**Comment by fastboot** [comment]
Hey @francesco-dipi, can you please assign this to @JanviRaina seems like there's already a PR and @JanviRaina beat me to it :) thanks!
